server:
  port: 8082
  servlet:
    context-path: /movie/product
spring:
  application:
    name: product-app
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: h2

  h2:
    console:
      enabled: true
      path: /h2-console

cnf:
  rest-template:
    connect-timeout: 4000
    connection-request-timeout: 4000
    response-timeout: 10000
