server:
  port: 8082
  servlet:
    context-path: /movie/product
spring:
  application:
    name: product-app
  output:
    ansi:
      enabled: ALWAYS

#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#    platform: h2

  datasource:
    url: jdbc:mysql://localhost:3307/sys?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  h2:
    console:
      enabled: false   # 이제 불필요하므로 비활성화
      path: /h2-console

cnf:
  rest-template:
    connect-timeout: 4000
    connection-request-timeout: 4000
    response-timeout: 10000
